### PR TITLE
a little update

### PR DESCRIPTION
**Pull request by paboldin**

### CODE REVIEW

**Comment by misc0110** [comment]
Could you split the pull request into multiple smaller pull requests? I don't like commit 077a8b1f7be1614ec12f363d55deb79e78accfd0 (phys_to_virt) as it silently "fails" when the user provides an invalid parameter (i.e., a virtual address). Further, it still does not catch if the address is actually an invalid physical address, e.g. something like 1TB. I would therefore not do any sanity checks in the function, or do correct sanity checks.

**Comment by paboldin** [comment]
Split. Closing this one.

**Comment by paboldin** [comment]
@misc0110 I can't check virtual vs physical address. I can check if the address provided is inside the virtual range though (which is 64TB).

**Comment by misc0110** [comment]
It would be possible to get the highest valid physical address from /proc/iomem. If the provided address is larger than that, it cannot be valid. However, this would require root privileges. This is why I didn't add any checks to the function. 
Do you see any reason to add a check inside the function?

**Comment by paboldin** [comment]
Just for the 64TB.

**Pull request closed without merging**
