### PR TITLE
Force 64bit mode

### PR DESCRIPTION
**Pull request by asgh**
This doesn't compile on a 32 bit system without this.

### CODE REVIEW

**Comment by misc0110** [comment]
What is the error for you when you try to compile? I tested it on a 32bit Ubuntu VM and it works for me.

**Comment by misc0110** [comment]
Can you check whether commit 064a2fa3f7c59e4ca275d1a7c0d6a5b9f73c7390 fixes the issue for you? Tried it in a 32-bit VM, as well as on a 32-bit netbook.

**Comment by asgh** [comment]
```
make -C libkdump
make[1]: Entering directory '/home/as/src/meltdown/libkdump'
gcc -c -fPIC libkdump.c -o libkdump.o -O3 -pthread -Wno-attributes
libkdump.c: In function ‘libkdump_read_tsx’:
libkdump.c:97:3: error: inconsistent operand constraints in an ‘asm’
   asm volatile("xor %%eax, %%eax\n"                                           \
   ^
libkdump.c:119:18: note: in expansion of macro ‘meltdown_nonull’
 #define MELTDOWN meltdown_nonull
                  ^
libkdump.c:478:7: note: in expansion of macro ‘MELTDOWN’
       MELTDOWN;
       ^
Makefile:7: recipe for target 'libkdump.o' failed
make[1]: *** [libkdump.o] Error 1
make[1]: Leaving directory '/home/as/src/meltdown/libkdump'
Makefile:12: recipe for target 'libkdump/libkdump.a' failed
make: *** [libkdump/libkdump.a] Error 2

```

**Comment by misc0110** [comment]
I'm trying to reproduce this, but no luck so far. Can you provide me some more details on your operating system, gcc version, and CPU?

**Comment by asgh** [comment]
Debian GNU/Linux 8
gcc version 4.9.2 (Debian 4.9.2-10) 
Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz

**Comment by crist0phe** [comment]
I have the same problem but I need to generate binaries for 32 bits architecture (also on Debian 7/8).

**Pull request merged**
